# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

# Use config.yml values for some configuration.
require 'yaml'
unless File.exist?("../../config.yml")
  raise 'Configuration file not found! Please copy example.config.yml to config.yml and try again.'
end
vconfig = YAML.load_file("../../config.yml")

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/debian10"
  config.ssh.insert_key = false
  config.vm.provider "virtualbox"

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 2
    v.linked_clone = true
    v.customize ['modifyvm', :id, '--audio', 'none']
  end

  # Define four VMs with static private IP addresses.
  boxes = [
    { :name => "kube1", :ip => "192.168.77.2" },
    { :name => "kube2", :ip => "192.168.77.3" },
    { :name => "kube3", :ip => "192.168.77.4" },
    { :name => "kube4", :ip => "192.168.77.5" }
  ]

  # Configure each of the VMs.
  boxes.each_with_index do |opts, index|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name] + ".pidramble.com"
      config.vm.network :private_network, ip: opts[:ip]

      # Provision all the VMs using Ansible after last VM is up.
      if index == boxes.size - 1
        config.vm.provision "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.playbook = "../../main.yml"
          ansible.inventory_path = "inventory"
          ansible.limit = "all"
          # ansible.raw_arguments = ["-vvv"]
          # ansible.tags = "nfs"
        end
      end
    end
  end

end
