---
# To run:
#   $ ansible-playbook -i ../../inventory gluster.yml

- hosts: webservers
  sudo: yes

  vars_files:
    - ../../playbooks/vars.yml
    - ../../playbooks/web/vars.yml

  tasks:
    - name: Ensure the Gluster mount is absent.
      mount:
        name: "{{ gluster_mount_dir }}"
        src: "{{ groups.webservers[0] }}:/{{ gluster_brick_name }}"
        fstype: glusterfs
        state: absent

    - name: Ensure the Gluster volume is absent.
      gluster_volume:
        state: absent
        name: "{{ gluster_brick_name }}"
        brick: "{{ gluster_brick_dir }}"
        host: "{{ inventory_hostname }}"
        force: yes
      run_once: true
      failed_when: false

    - name: Stop gluster.
      service: name=glusterfs-server state=stopped

    - name: Clear out gluster brick.
      shell: "rm -rf /srv/gluster/brick"
