---
# To run:
#   $ ansible-playbook -i ../../inventory php.yml

- hosts: webservers
  become: yes

  tasks:
    - name: Ensure php-fpm is stopped.
      service: name=php5-fpm state=stopped
      failed_when: false

    - name: Ensure PHP packages are completely removed.
      apt:
        name: "php*"
        state: absent
        purge: yes

    - name: Ensure PHP directories are completely removed.
      file:
        path: /opt/php
        state: absent
      with_items:
        - /opt/php
        - /etc/php5

    - name: Restart nginx.
      service: name=nginx state=restarted

- hosts: balancer
  gather_facts: no
  become: yes

  tasks:
    - name: Empty nginx reverse proxy cache.
      shell: "rm -rf /var/cache/nginx/*"

    - name: Restart nginx.
      service: name=nginx state=restarted
